Fix test/replay.py (#1014)
 * Scapy v2 requires import from scapy.all instead of scapy.
   http://www.secdev.org/projects/scapy/doc/installation.html         

   * Make this work with both scapy v1 and v2:
     Check if conf is defined, otherwise import scapy v2 and retry 

 * Ignore unpack errors with short packages:
   struct.error: unpack requires a string argument of length 6



git-svn-id: http://svn.aircrack-ng.org/trunk@2251 28c6078b-6c39-48e3-add9-af49d547ecab