Fixed Cygwin install error due to undefined reference to GUID_DEVCLASS_NET (Closes: #1616).
git-svn-id: http://svn.aircrack-ng.org/trunk@2676 28c6078b-6c39-48e3-add9-af49d547ecab